apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: allure-api-tests
    component: allure-api-tests
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.REPLICA_COUNT }}
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 3
        maxUnavailable: 0
  selector:
    matchLabels:
      app: allure-api-tests
      component: allure-api-tests
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}-web
      labels:
        app: allure-api-tests
        component: allure-api-tests
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry
      initContainers:
        - name: init-sysctl
          image: cr.yandex/crpk51ud2cjku2i8e2b6/busybox:latest
          command:
          - /bin/sh
          - -c
          - |
            sysctl -w net.core.somaxconn=60000
          securityContext:
            privileged: true
      containers:
        - image: {{ .Values.APP_IMAGE }}
          imagePullPolicy: Always
          name: allure-api-tests
          resources:
            limits:
              memory: "500Mi"
            requests:
              cpu: 30m
              memory: "500Mi"

