---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: allure-api-tests
    component: allure-api-tests
    release: {{ .Release.Name }}
  ports:
  - name: allure-api-tests
    port: 80
    targetPort: 5050
